import AccountTreeRoundedIcon from "@mui/icons-material/AccountTreeRounded";
import AutoGraphRoundedIcon from "@mui/icons-material/AutoGraphRounded";
import BarChartRoundedIcon from "@mui/icons-material/BarChartRounded";
import QueryStatsRoundedIcon from "@mui/icons-material/QueryStatsRounded";
import ShieldRoundedIcon from "@mui/icons-material/ShieldRounded";
import ShowChartRoundedIcon from "@mui/icons-material/ShowChartRounded";
import TimelineRoundedIcon from "@mui/icons-material/TimelineRounded";
import TrackChangesRoundedIcon from "@mui/icons-material/TrackChangesRounded";
import type { LearningIcon } from "@/components/learning/types";

export interface GuideSection {
  id: string;
  label: string;
  description: string;
  formula: string;
  interpretation: string;
  takeaway: string;
  icon: LearningIcon;
}

export const guideSections: GuideSection[] = [
  {
    id: "sharpe-ratio",
    label: "Sharpe Ratio",
    icon: ShowChartRoundedIcon,
    description:
      "The Sharpe Ratio measures risk-adjusted returns by comparing an investment's excess return with its volatility. It helps investors understand how much additional return they receive for taking extra risk.",
    formula:
      "Sharpe Ratio = (Portfolio Return - Risk-Free Rate) / Portfolio Standard Deviation",
    interpretation:
      "A higher Sharpe Ratio indicates better risk-adjusted performance. A ratio above 1.0 is usually considered good, above 2.0 very good, and above 3.0 excellent. A negative value means the investment underperformed the risk-free rate.",
    takeaway:
      "Use Sharpe Ratio to compare risk-adjusted returns across investments with different volatility profiles.",
  },
  {
    id: "sortino-ratio",
    label: "Sortino Ratio",
    icon: TrackChangesRoundedIcon,
    description:
      "The Sortino Ratio is a variation of the Sharpe Ratio that only considers downside volatility. It focuses on harmful volatility rather than all price movement.",
    formula:
      "Sortino Ratio = (Portfolio Return - Target Return) / Downside Deviation",
    interpretation:
      "A higher Sortino Ratio is better. Values above 2.0 are generally strong. This measure is especially useful when investors care more about downside losses than upside fluctuations.",
    takeaway:
      "Use Sortino Ratio when the key question is whether returns compensate you for downside risk.",
  },
  {
    id: "alpha",
    label: "Alpha",
    icon: AutoGraphRoundedIcon,
    description:
      "Alpha measures investment performance relative to a market benchmark. It estimates the return generated by investment decisions after accounting for market exposure.",
    formula:
      "Alpha = Actual Return - (Risk-Free Rate + Beta x (Market Return - Risk-Free Rate))",
    interpretation:
      "Positive alpha suggests outperformance after adjusting for risk, while negative alpha suggests underperformance. An alpha of +2.0 means the portfolio outperformed the expected return by 2 percentage points.",
    takeaway:
      "Consistent positive alpha can indicate value added beyond passive benchmark exposure.",
  },
  {
    id: "beta",
    label: "Beta",
    icon: BarChartRoundedIcon,
    description:
      "Beta measures an asset's volatility relative to the broader market. It indicates how strongly a stock tends to move with market changes.",
    formula:
      "Beta = Covariance(Stock Returns, Market Returns) / Variance(Market Returns)",
    interpretation:
      "A beta of 1.0 means the stock tends to move with the market. Beta above 1.0 implies higher market sensitivity, while beta below 1.0 implies lower market sensitivity.",
    takeaway:
      "Use beta to align portfolio exposure with your risk tolerance and market outlook.",
  },
  {
    id: "volatility",
    label: "Volatility",
    icon: TimelineRoundedIcon,
    description:
      "Volatility measures how much returns vary over time, usually expressed as standard deviation. It helps quantify uncertainty around future price movement.",
    formula: "Volatility = Standard Deviation of Returns x Square Root of Periods",
    interpretation:
      "Higher volatility means larger price swings and higher uncertainty. Lower volatility usually indicates more stable returns, but it does not guarantee safety.",
    takeaway:
      "Volatility is a risk signal, but it must be evaluated alongside expected return and investment horizon.",
  },
  {
    id: "max-drawdown",
    label: "Max Drawdown",
    icon: ShieldRoundedIcon,
    description:
      "Maximum Drawdown measures the largest peak-to-trough decline in portfolio value over a period. It shows the worst loss an investor would have experienced during that window.",
    formula: "Max Drawdown = (Trough Value - Peak Value) / Peak Value x 100%",
    interpretation:
      "A maximum drawdown of -25% means the portfolio fell 25% from its highest point. Smaller drawdowns generally indicate stronger downside protection.",
    takeaway:
      "Use drawdown to test whether a strategy's worst historical loss fits your emotional and financial risk capacity.",
  },
  {
    id: "value-at-risk",
    label: "Value at Risk",
    icon: QueryStatsRoundedIcon,
    description:
      "Value at Risk estimates the maximum expected loss over a specified period at a given confidence level. It is widely used in risk management.",
    formula: "VaR = Portfolio Value x Z-score x Standard Deviation",
    interpretation:
      "A 95% VaR of $100,000 means there is a 95% probability the portfolio will not lose more than $100,000 over the selected period. It does not describe losses beyond that threshold.",
    takeaway:
      "VaR is useful for setting risk limits, but it should be paired with tail-risk analysis.",
  },
  {
    id: "efficient-frontier",
    label: "Efficient Frontier",
    icon: AccountTreeRoundedIcon,
    description:
      "The Efficient Frontier represents portfolios that offer the highest expected return for a given risk level or the lowest risk for a given expected return.",
    formula:
      "Optimization: Maximize Return for Given Risk or Minimize Risk for Given Return",
    interpretation:
      "Portfolios on the frontier are considered efficient. Portfolios below it are inefficient because they either take too much risk for the return or earn too little return for the risk.",
    takeaway:
      "The Efficient Frontier explains why diversification can improve the risk-return tradeoff.",
  },
];

export const guideSectionIds = guideSections.map((section) => section.id);
