import React, { useState } from 'react';
import Sidebar from '@/components/sidebar';

// ── Types ──────────────────────────────────────────────────────────────────────
interface GuideSection {
  id: string;
  label: string;
  icon: string;
  description: string;
  formula: string;
  interpretation: string;
  takeaway: string;
}

// ── Data ───────────────────────────────────────────────────────────────────────
const guideSections: GuideSection[] = [
  {
    id: 'sharpe-ratio',
    label: 'Sharpe Ratio',
    icon: 'bx-trending-up',
    description:
      'The Sharpe Ratio measures risk-adjusted returns by comparing the excess return of an investment to its volatility. It helps investors understand how much additional return they receive for the extra volatility endured by holding a risky asset.',
    formula: 'Sharpe Ratio = (Portfolio Return − Risk-Free Rate) / Portfolio Standard Deviation',
    interpretation:
      'A higher Sharpe Ratio indicates better risk-adjusted performance. Generally, a ratio above 1.0 is considered good, above 2.0 is very good, and above 3.0 is excellent. A negative ratio indicates the investment underperformed the risk-free rate.',
    takeaway:
      "Use Sharpe Ratio to compare risk-adjusted returns across different investments. It's one of the most widely used metrics in portfolio management.",
  },
  {
    id: 'sortino-ratio',
    label: 'Sortino Ratio',
    icon: 'bx-target-lock',
    description:
      'The Sortino Ratio is a variation of the Sharpe Ratio that only considers downside volatility, focusing on harmful volatility rather than total volatility. This provides a more accurate measure of downside risk.',
    formula: 'Sortino Ratio = (Portfolio Return - Target Return) / Downside Deviation',
    interpretation:
      'Similar to the Sharpe Ratio, a higher Sortino Ratio is better. Values above 2.0 are considered very good. The Sortino Ratio is particularly useful for investors concerned with downside risk rather than overall volatility.',
    takeaway:
      'Sortino Ratio is preferred when you\'re specifically concerned about downside risk, as it doesn\'t penalize upside volatility.',
  },
  {
    id: 'alpha',
    label: 'Alpha',
    icon: 'bx-pulse',
    description:
      'Alpha measures an investment\'s performance relative to a market index or benchmark. It represents the excess return generated by a portfolio manager\'s investment decisions, independent of market movements.',
    formula: 'Alpha = Actual Return - (Risk-Free Rate + Beta × (Market Return - Risk-Free Rate))',
    interpretation:
      'Positive alpha indicates outperformance relative to the benchmark after adjusting for risk, while negative alpha suggests underperformance. An alpha of +2.0 means the portfolio outperformed the benchmark by 2%.',
    takeaway:
      'Consistent positive alpha is the hallmark of skilled active management. It shows value added beyond what could be achieved through passive index investing.',
  },
  {
    id: 'beta',
    label: 'Beta',
    icon: 'bx-bar-chart-alt',
    description:
      'Beta measures an asset\'s volatility relative to the overall market. It indicates how much a stock\'s price tends to move in relation to market movements, providing insight into systematic risk.',
    formula: 'Beta = Covariance(Stock Returns, Market Returns) / Variance(Market Returns)',
    interpretation:
      'A beta of 1.0 means the stock moves in line with the market. Beta > 1.0 indicates higher volatility than the market, while beta < 1.0 suggests lower volatility. A beta of 1.5 means the stock is 50% more volatile than the market.',
    takeaway:
      'Understanding beta helps you build portfolios aligned with your risk tolerance. High-beta stocks amplify both gains and losses in bull and bear markets.',
  },
  {
    id: 'volatility',
    label: 'Volatility',
    icon: 'bx-pulse',
    description:
      'Volatility measures the degree of variation in a stock\'s returns over time, typically expressed as standard deviation. It quantifies the uncertainty or risk associated with the size of changes in a security\'s value.',
    formula: 'Volatility = Standard Deviation of Returns × √(Number of Periods)',
    interpretation:
      'Higher volatility indicates greater price fluctuations and risk. Annual volatility of 20% means approximately 68% of returns will fall within ±20% of the average return. Lower volatility suggests more stable, predictable returns.',
    takeaway:
      'While volatility indicates risk, it\'s not inherently bad. Higher volatility can be acceptable if compensated by higher expected returns.',
  },
  {
    id: 'max-drawdown',
    label: 'Max Drawdown',
    icon: 'bx-shield',
    description:
      'Maximum Drawdown measures the largest peak-to-trough decline in portfolio value during a specific time period. It represents the worst-case loss an investor would have experienced during that period.',
    formula: 'Max Drawdown = (Trough Value - Peak Value) / Peak Value × 100%',
    interpretation:
      'A maximum drawdown of -25% means the portfolio lost 25% from its highest point. Lower (less negative) drawdowns indicate better downside protection. This metric is crucial for understanding worst-case scenarios and risk tolerance.',
    takeaway:
      'Maximum Drawdown is crucial for understanding your emotional tolerance for losses. Ensure your portfolio\'s potential drawdown aligns with your risk capacity.',
  },
  {
    id: 'value-at-risk',
    label: 'Value at Risk (VaR)',
    icon: 'bx-shield',
    description:
      'Value at Risk estimates the maximum potential loss in portfolio value over a specific time period for a given confidence level. It\'s a widely used risk management tool in financial institutions.',
    formula: 'VaR = Portfolio Value × Z-score × Standard Deviation',
    interpretation:
      'A 95% VaR of $100,000 means there\'s a 95% probability the portfolio won\'t lose more than $100,000 over the specified period. Higher VaR indicates greater potential losses. VaR is useful for setting risk limits and capital requirements.',
    takeaway:
      'VaR provides a single, easy-to-understand number for risk exposure. However, it doesn\'t predict losses beyond the confidence level (tail risk).',
  },
  {
    id: 'efficient-frontier',
    label: 'Efficient Frontier',
    icon: 'bx-target-lock',
    description:
      'The Efficient Frontier represents the set of optimal portfolios that offer the highest expected return for a given level of risk or the lowest risk for a given expected return. It\'s a key concept in modern portfolio theory.',
    formula: 'Optimization: Maximize Return for Given Risk or Minimize Risk for Given Return',
    interpretation:
      'Portfolios on the efficient frontier are considered optimal. Those below the frontier are suboptimal (inefficient). The tangency portfolio, where a line from the risk-free rate touches the frontier, represents the optimal risky portfolio.',
    takeaway:
      'The Efficient Frontier demonstrates that diversification is the only \'free lunch\' in investing—you can reduce risk without sacrificing expected return.',
  },
];

// ── Icon map for nav ───────────────────────────────────────────────────────────
const navIcons: Record<string, string> = {
  'sharpe-ratio':     'bx-trending-up',
  'sortino-ratio':    'bx-target-lock',
  'alpha':            'bx-pulse',
  'beta':             'bx-bar-chart-alt',
  'volatility':       'bx-pulse',
  'max-drawdown':     'bx-shield',
  'value-at-risk':    'bx-shield',
  'efficient-frontier': 'bx-target-lock',
};

// ── Info Card ──────────────────────────────────────────────────────────────────
interface InfoCardProps {
  iconClass: string;
  iconColor: string;
  title: string;
  children: React.ReactNode;
  accentBg?: string;
}

const InfoCard: React.FC<InfoCardProps> = ({ iconClass, iconColor, title, children, accentBg }) => (
  <div
    style={{
      backgroundColor: accentBg ?? '#09090B',
      border: `1px solid ${accentBg ? '#1D2A5C' : '#27272A'}`,
      borderRadius: '12px',
      padding: '1.5rem',
      marginBottom: '1rem',
    }}
  >
    <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.75rem' }}>
      <i className={`bx ${iconClass}`} style={{ fontSize: '1.3rem', color: iconColor }} />
      <span style={{ fontWeight: 700, fontSize: '1.05rem', color: '#ffffff' }}>{title}</span>
    </div>
    {children}
  </div>
);

// ── Main Component ─────────────────────────────────────────────────────────────
const Guide: React.FC = () => {
  const [activeId, setActiveId] = useState<string>('sharpe-ratio');
  const active = guideSections.find((s) => s.id === activeId) ?? guideSections[0];
  const [sidebarOpen, setSidebarOpen] = useState(false);
  

  return (
    <div style={{ 
      marginLeft: sidebarOpen ? '200px' : '50px', 
      transition: 'margin-left 0.3s ease', 
      display: 'flex', 
      height: '100vh', 
      backgroundColor: '#0f1117', 
      color: '#ffffff' }}>
      
      {/* Left: App Sidebar */}
      <Sidebar onHoverChange={setSidebarOpen} />

      {/* Middle: Guide nav */}
      <div
        style={{
          width: '280px',
          flexShrink: 0,
          borderRight: '1px solid #27272A',
          padding: '1.5rem 1.75rem',
          overflowY: 'auto',
          backgroundColor: '#09090B',
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '1.5rem', paddingLeft: '0.5rem' }}>
          <i className="bx bx-book-open" style={{ fontSize: '1.3rem', color: '#447DF7' }} />
          <span style={{ fontWeight: 700, fontSize: '1.15rem' }}>Guide</span>
        </div>

        {/* Nav list */}
        <nav>
          {guideSections.map((section) => {
            const isActive = section.id === activeId;
            return (
              <button
                key={section.id}
                onClick={() => setActiveId(section.id)}
                style={{
                  width: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.65rem',
                  padding: '0.75rem 1rem',
                  marginBottom: '0.35rem',
                  borderRadius: '8px',
                  border: isActive ? '1px solid #203773' : '1px solid transparent',
                  cursor: 'pointer',
                  textAlign: 'left',
                  fontSize: '0.95rem',
                  fontWeight: isActive ? 700 : 400,
                  backgroundColor: isActive ? '#101939' : 'transparent',
                  color: isActive ? '#ffffff' : '#9F9FA8',
                  transition: 'background-color 0.15s, color 0.15s',
                }}
                onMouseEnter={(e) => {
                  if (!isActive) {
                    (e.currentTarget as HTMLButtonElement).style.backgroundColor = '#18181B';
                    (e.currentTarget as HTMLButtonElement).style.color = '#ffffff';
                  }
                }}
                onMouseLeave={(e) => {
                  if (!isActive) {
                    (e.currentTarget as HTMLButtonElement).style.backgroundColor = 'transparent';
                    (e.currentTarget as HTMLButtonElement).style.color = '#9aa3b8';
                  }
                }}
              >
                <i className={`bx ${navIcons[section.id]}`}
                  style={{ fontSize: '1rem', flexShrink: 0, color: isActive ? '#447DF7' : '#9F9FA8' }}
                />
                {section.label}
              </button>
            );
          })}
        </nav>
      </div>

      {/* Right: Content */}
      <main
        style={{
          flex: 1,
          overflowY: 'auto',
          padding: '2.5rem 2.5rem',
          backgroundColor: '#000000',
        }}
      >
        <h1 style={{ fontSize: '2.2rem', fontWeight: 800, marginBottom: '0.5rem' }}>
          {active.label}
        </h1>
        <p style={{ color: '#9F9FA8', fontSize: '1rem', marginBottom: '2rem' }}>
          {active.description}
        </p>

        {/* Formula */}
        <InfoCard iconClass="bx-bar-chart-alt-2" iconColor="#447DFC" title="Formula">
          <div
            style={{
              backgroundColor: '#050506',
              borderRadius: '8px',
              border: '1px solid #27272A',
              borderColor: '#27272A',
              padding: '1rem 1.25rem',
              fontFamily: 'monospace',
              fontSize: '0.9rem',
              color: '#65A0FD',
              lineHeight: 1.6,
            }}
          >
            {active.formula}
          </div>
        </InfoCard>

        {/* Interpretation */}
        <InfoCard iconClass="bx-target-lock" iconColor="#A04DFD" title="Interpretation">
          <p style={{ color: '#9aa3b8', lineHeight: 1.7, fontSize: '0.95rem' }}>
            {active.interpretation}
          </p>
        </InfoCard>

        {/* Key Takeaway */}
        <InfoCard iconClass="bx-pulse" iconColor="#65A0FD" title="Key Takeaway" accentBg="#07051a">
          <p style={{ color: '#9aa3b8', lineHeight: 1.7, fontSize: '0.95rem' }}>
            {active.takeaway}
          </p>
        </InfoCard>
      </main>
    </div>
  );
};

export default Guide;