// File purpose: Defines the static Guide topic content rendered by the Guide feature.
import AccountTreeRoundedIcon from "@mui/icons-material/AccountTreeRounded";
import AutoGraphRoundedIcon from "@mui/icons-material/AutoGraphRounded";
import BarChartRoundedIcon from "@mui/icons-material/BarChartRounded";
import QueryStatsRoundedIcon from "@mui/icons-material/QueryStatsRounded";
import ShieldRoundedIcon from "@mui/icons-material/ShieldRounded";
import ShowChartRoundedIcon from "@mui/icons-material/ShowChartRounded";
import TimelineRoundedIcon from "@mui/icons-material/TimelineRounded";
import TrackChangesRoundedIcon from "@mui/icons-material/TrackChangesRounded";
import type { GuideSectionCollection } from "../types";

export const guideSections = Object.freeze([
  {
    id: "sharpe-ratio",
    label: "Sharpe Ratio",
    icon: ShowChartRoundedIcon,
    description:
      "The Sharpe Ratio measures risk-adjusted returns by comparing an investment's excess return with its volatility. It helps investors understand how much additional return they receive for taking extra risk.",
    formula:
      "Sharpe Ratio = (Portfolio Return - Risk-Free Rate) / Portfolio Standard Deviation",
    interpretation:
      "A higher Sharpe Ratio indicates better risk-adjusted performance. A ratio above 1.0 is usually considered good, above 2.0 very good, and above 3.0 excellent. A negative value means the investment underperformed the risk-free rate.",
    takeaway:
      "Use Sharpe Ratio to compare risk-adjusted returns across investments with different volatility profiles.",
  },
  {
    id: "sortino-ratio",
    label: "Sortino Ratio",
    icon: TrackChangesRoundedIcon,
    description:
      "FIT measures downside deviation from the daily risk-free target across the full return sample, so upside days remain in the denominator as zero shortfall rather than being discarded.",
    formula:
      "Sortino Ratio = (Annualised Average Return - Risk-Free Rate) / Annualised Downside Deviation",
    interpretation:
      "Higher is better only across comparable periods and assumptions. If no return falls below the daily target, FIT reports an unbounded ratio explicitly instead of inventing a finite score.",
    takeaway:
      "Use Sortino Ratio when the key question is whether returns compensate you for downside risk.",
  },
  {
    id: "alpha",
    label: "Alpha",
    icon: AutoGraphRoundedIcon,
    description:
      "Alpha measures investment performance relative to a market benchmark. It estimates the return generated by investment decisions after accounting for market exposure.",
    formula:
      "Alpha = Actual Return - (Risk-Free Rate + Beta x (Market Return - Risk-Free Rate))",
    interpretation:
      "FIT returns annualised alpha as a decimal. Positive alpha suggests risk-adjusted outperformance, while negative alpha suggests underperformance. An alpha of 0.02 means the investment outperformed its CAPM expected return by about 2 percentage points over a year.",
    takeaway:
      "Consistent positive alpha can indicate value added beyond passive benchmark exposure.",
  },
  {
    id: "beta",
    label: "Beta",
    icon: BarChartRoundedIcon,
    description:
      "Beta measures an asset's volatility relative to the broader market. It indicates how strongly a stock tends to move with market changes.",
    formula:
      "Beta = Covariance(Stock Returns, Market Returns) / Variance(Market Returns)",
    interpretation:
      "A beta of 1.0 means the stock tends to move with the market. Beta above 1.0 implies higher market sensitivity, while beta below 1.0 implies lower market sensitivity.",
    takeaway:
      "Use beta to align portfolio exposure with your risk tolerance and market outlook.",
  },
  {
    id: "volatility",
    label: "Volatility",
    icon: TimelineRoundedIcon,
    description:
      "Volatility measures how much returns vary over time, usually expressed as standard deviation. It helps quantify uncertainty around future price movement.",
    formula: "Volatility = Standard Deviation of Returns x Square Root of Periods",
    interpretation:
      "Higher volatility means larger price swings and higher uncertainty. Lower volatility usually indicates more stable returns, but it does not guarantee safety.",
    takeaway:
      "Volatility is a risk signal, but it must be evaluated alongside expected return and investment horizon.",
  },
  {
    id: "max-drawdown",
    label: "Max Drawdown",
    icon: ShieldRoundedIcon,
    description:
      "FIT plots the drawdown path across the selected date range. Each point measures how far the current price is below its highest price so far, and the lowest point in the path is the Maximum Drawdown.",
    formula:
      "Drawdown(t) = (Current Price - Highest Price So Far) / Highest Price So Far; Max Drawdown = minimum Drawdown(t)",
    interpretation:
      "A drawdown value of -0.25 means the price is 25% below its previous peak (-25%). The most negative value in the selected period is the Maximum Drawdown; a return to 0 means a new peak was reached.",
    takeaway:
      "Read the full path to see both the depth and duration of declines, then use its lowest point to judge the worst historical drawdown.",
  },
  {
    id: "value-at-risk",
    label: "Value at Risk",
    icon: QueryStatsRoundedIcon,
    description:
      "FIT uses historical Value at Risk to report the positive magnitude of a lower-tail one-day loss threshold from observed daily returns.",
    formula:
      "Historical VaR loss magnitude = max(0, - selected lower-tail return percentile)",
    interpretation:
      "At the selected confidence, a Historical VaR of 3% means only the chosen tail probability of observed daily returns fell below -3%. Lower is better, but this is a threshold rather than a maximum or dollar-loss forecast.",
    takeaway:
      "Use FIT's Historical VaR as one downside threshold and pair it with Max Drawdown to understand losses beyond that threshold.",
  },
  {
    id: "efficient-frontier",
    label: "Efficient Frontier",
    icon: AccountTreeRoundedIcon,
    description:
      "FIT deterministically samples 10,000 long-only portfolios from a Dirichlet distribution and plots annualised estimated return against risk. The cloud is a sampled opportunity set, not a mathematically optimized frontier.",
    formula:
      "Each sample: Expected Return = Weights x Annualised Mean Returns; Risk = Square Root of (Weights x Covariance Matrix x Weights)",
    interpretation:
      "Each point is one sampled allocation whose non-negative weights sum to 100%. FIT labels the best sampled Sharpe and lowest sampled volatility points; neither is claimed to be the exact optimum.",
    takeaway:
      "Use the simulated cloud to explore diversification and risk-return trade-offs, while treating its apparent frontier as an approximation rather than an optimizer result.",
  },
] satisfies GuideSectionCollection);
