// File purpose: Defines the static Guide topic content rendered by the Guide feature.
import AccountTreeRoundedIcon from "@mui/icons-material/AccountTreeRounded";
import AutoGraphRoundedIcon from "@mui/icons-material/AutoGraphRounded";
import BarChartRoundedIcon from "@mui/icons-material/BarChartRounded";
import QueryStatsRoundedIcon from "@mui/icons-material/QueryStatsRounded";
import ShieldRoundedIcon from "@mui/icons-material/ShieldRounded";
import ShowChartRoundedIcon from "@mui/icons-material/ShowChartRounded";
import TimelineRoundedIcon from "@mui/icons-material/TimelineRounded";
import TrackChangesRoundedIcon from "@mui/icons-material/TrackChangesRounded";
import type { GuideSectionCollection } from "../types";

export const guideSections = Object.freeze([
  {
    id: "sharpe-ratio",
    label: "Sharpe Ratio",
    icon: ShowChartRoundedIcon,
    description:
      "The Sharpe Ratio measures risk-adjusted returns by comparing an investment's excess return with its volatility. It helps investors understand how much additional return they receive for taking extra risk.",
    formula:
      "Sharpe Ratio = (Portfolio Return - Risk-Free Rate) / Portfolio Standard Deviation",
    interpretation:
      "A higher Sharpe Ratio indicates better risk-adjusted performance. A ratio above 1.0 is usually considered good, above 2.0 very good, and above 3.0 excellent. A negative value means the investment underperformed the risk-free rate.",
    takeaway:
      "Use Sharpe Ratio to compare risk-adjusted returns across investments with different volatility profiles.",
  },
  {
    id: "sortino-ratio",
    label: "Sortino Ratio",
    icon: TrackChangesRoundedIcon,
    description:
      "The Sortino Ratio is a variation of the Sharpe Ratio that only considers downside volatility. It focuses on harmful volatility rather than all price movement.",
    formula:
      "Sortino Ratio = (Annualised Average Return - Risk-Free Rate) / Annualised Downside Deviation",
    interpretation:
      "A higher Sortino Ratio is better. Values above 2.0 are generally strong. This measure is especially useful when investors care more about downside losses than upside fluctuations.",
    takeaway:
      "Use Sortino Ratio when the key question is whether returns compensate you for downside risk.",
  },
  {
    id: "alpha",
    label: "Alpha",
    icon: AutoGraphRoundedIcon,
    description:
      "Alpha measures investment performance relative to a market benchmark. It estimates the return generated by investment decisions after accounting for market exposure.",
    formula:
      "Alpha = Actual Return - (Risk-Free Rate + Beta x (Market Return - Risk-Free Rate))",
    interpretation:
      "FIT returns annualised alpha as a decimal. Positive alpha suggests risk-adjusted outperformance, while negative alpha suggests underperformance. An alpha of 0.02 means the investment outperformed its CAPM expected return by about 2 percentage points over a year.",
    takeaway:
      "Consistent positive alpha can indicate value added beyond passive benchmark exposure.",
  },
  {
    id: "beta",
    label: "Beta",
    icon: BarChartRoundedIcon,
    description:
      "Beta measures an asset's volatility relative to the broader market. It indicates how strongly a stock tends to move with market changes.",
    formula:
      "Beta = Covariance(Stock Returns, Market Returns) / Variance(Market Returns)",
    interpretation:
      "A beta of 1.0 means the stock tends to move with the market. Beta above 1.0 implies higher market sensitivity, while beta below 1.0 implies lower market sensitivity.",
    takeaway:
      "Use beta to align portfolio exposure with your risk tolerance and market outlook.",
  },
  {
    id: "volatility",
    label: "Volatility",
    icon: TimelineRoundedIcon,
    description:
      "Volatility measures how much returns vary over time, usually expressed as standard deviation. It helps quantify uncertainty around future price movement.",
    formula: "Volatility = Standard Deviation of Returns x Square Root of Periods",
    interpretation:
      "Higher volatility means larger price swings and higher uncertainty. Lower volatility usually indicates more stable returns, but it does not guarantee safety.",
    takeaway:
      "Volatility is a risk signal, but it must be evaluated alongside expected return and investment horizon.",
  },
  {
    id: "max-drawdown",
    label: "Max Drawdown",
    icon: ShieldRoundedIcon,
    description:
      "FIT plots the drawdown path across the selected date range. Each point measures how far the current price is below its highest price so far, and the lowest point in the path is the Maximum Drawdown.",
    formula:
      "Drawdown(t) = (Current Price - Highest Price So Far) / Highest Price So Far; Max Drawdown = minimum Drawdown(t)",
    interpretation:
      "A drawdown value of -0.25 means the price is 25% below its previous peak (-25%). The most negative value in the selected period is the Maximum Drawdown; a return to 0 means a new peak was reached.",
    takeaway:
      "Read the full path to see both the depth and duration of declines, then use its lowest point to judge the worst historical drawdown.",
  },
  {
    id: "value-at-risk",
    label: "Value at Risk",
    icon: QueryStatsRoundedIcon,
    description:
      "FIT uses historical Value at Risk to estimate a lower-tail one-day return threshold from the observed daily returns in the selected date range.",
    formula:
      "Historical VaR (95% confidence) = 5th percentile of observed daily returns",
    interpretation:
      "A Historical VaR of -3% means 5% of the observed daily returns were at or below -3%. It is a historical return threshold, not a guaranteed maximum loss or a dollar-loss forecast.",
    takeaway:
      "Use FIT's Historical VaR as one downside threshold and pair it with Max Drawdown to understand losses beyond that threshold.",
  },
  {
    id: "efficient-frontier",
    label: "Efficient Frontier",
    icon: AccountTreeRoundedIcon,
    description:
      "FIT currently simulates 10,000 random long-only portfolios and plots their annualised expected return against risk. The result is a portfolio cloud that approximates the opportunity set; it is not a mathematically filtered frontier.",
    formula:
      "Each sample: Expected Return = Weights x Annualised Mean Returns; Risk = Square Root of (Weights x Covariance Matrix x Weights)",
    interpretation:
      "Each point is one random allocation whose weights sum to 100%. The upper-left boundary of the cloud can approximate efficient choices, but FIT does not currently filter or optimize those boundary points.",
    takeaway:
      "Use the simulated cloud to explore diversification and risk-return trade-offs, while treating its apparent frontier as an approximation rather than an optimizer result.",
  },
] satisfies GuideSectionCollection);
